spring:
  application:
    name: poc-java-spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5
        options:
          temperature: 0.3
      embedding:
        model: nomic-embed-text
